[general]
working_directory = "C:\\Users\\Bjarne"
import = ["C:\\Users\\Bjarne\\AppData\\Roaming\\alacritty\\catppuccin-mocha.toml"]

[window]
title = "Terminal"
dynamic_title = false
decorations = "Full"
dimensions = { columns = 120, lines = 40 }
position = { x = 470, y = 200 }
padding = { x = 10, y = 10 }
dynamic_padding = true
opacity = 0.95
startup_mode = "Windowed"

[font]
normal = { family = "Consolas", style = "Regular" }
size = 11

[cursor]
style = { shape = "Underline", blinking = "Never"}

[terminal]
shell = { program = "pwsh", args = ["-NoLogo", "-NoExit", "-Command \"& {fastfetch}\""] }